"""DRIFTIQ — Public student view.
Read-only, no login: GET /notes/<slug> renders a published note as a
standalone page. Draft or unknown slugs 404 — nothing reaches students
without the professor's explicit Publish.
"""
from __future__ import annotations
import html
import re

from fastapi import APIRouter, Depends
from fastapi.responses import HTMLResponse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

import db
import models

router = APIRouter(tags=["public"])


def md_to_html(md: str) -> str:
    """Tiny markdown renderer for the note format extract.py emits
    (#/##/### headings, - lists, **bold**, `code`)."""
    def inline(s: str) -> str:
        s = html.escape(s)
        s = re.sub(r"`([^`]+)`", r"<code>\1</code>", s)
        s = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", s)
        return s

    out: list[str] = []
    in_list = False

    def close():
        nonlocal in_list
        if in_list:
            out.append("</ul>")
            in_list = False

    for raw in (md or "").split("\n"):
        line = raw.rstrip()
        if not line:
            close()
            continue
        if line.startswith("### "):
            close(); out.append(f"<h3>{inline(line[4:])}</h3>")
        elif line.startswith("## "):
            close(); out.append(f"<h2>{inline(line[3:])}</h2>")
        elif line.startswith("# "):
            close(); out.append(f"<h1>{inline(line[2:])}</h1>")
        elif line.startswith("- "):
            if not in_list:
                out.append("<ul>")
                in_list = True
            out.append(f"<li>{inline(line[2:])}</li>")
        else:
            close(); out.append(f"<p>{inline(line)}</p>")
    close()
    return "\n".join(out)


_PAGE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
  :root{{ --navy:#0f2a4d; --blue:#4a7ab8; --gold:#c9a836; --muted:#6b7280; --line:#e5e7eb; }}
  *{{box-sizing:border-box; margin:0; padding:0;}}
  body{{font-family:Georgia,'Times New Roman',serif; color:#1f2937; background:#fdfdfc; line-height:1.7;}}
  .topbar{{background:var(--navy); color:#fff; padding:12px 24px;
    font-family:'Segoe UI',Arial,sans-serif; font-weight:800; letter-spacing:.02em;}}
  .topbar b{{color:#a8c9ff;}}
  .accent{{height:3px; background:linear-gradient(90deg,var(--blue),var(--gold));}}
  article{{max-width:760px; margin:0 auto; padding:40px 24px 80px;}}
  .meta{{font-family:'Segoe UI',Arial,sans-serif; font-size:13px; color:var(--muted);
    margin-bottom:28px; padding-bottom:14px; border-bottom:1px solid var(--line);}}
  h1{{font-size:30px; color:var(--navy); line-height:1.25; margin-bottom:10px;}}
  h2{{font-size:21px; color:var(--navy); margin:34px 0 10px;
    padding-bottom:6px; border-bottom:2px solid var(--gold);}}
  h3{{font-size:17px; color:var(--blue); margin:22px 0 6px;}}
  p{{margin:10px 0;}}
  ul{{margin:10px 0 10px 26px;}}
  li{{margin:6px 0;}}
  code{{font-family:'Courier New',monospace; background:#f3f4f6; padding:2px 6px;
    border-radius:4px; font-size:.9em;}}
  strong{{color:var(--navy);}}
  footer{{font-family:'Segoe UI',Arial,sans-serif; text-align:center; font-size:12px;
    color:var(--muted); padding:24px; border-top:1px solid var(--line);}}
</style>
</head>
<body>
<div class="topbar">DRIFT<b>IQ</b></div>
<div class="accent"></div>
<article>
  <div class="meta">{meta}</div>
  {body}
</article>
<footer>Generated by DRIFTIQ — AI-powered classroom notes, reviewed and published by the professor.</footer>
</body>
</html>"""


@router.get("/notes/{slug}", response_class=HTMLResponse)
async def public_note(slug: str, session: AsyncSession = Depends(db.get_session)):
    row = (
        await session.execute(
            select(models.Note, models.Lecture)
            .join(models.Lecture, models.Lecture.id == models.Note.lecture_id)
            .where(models.Note.slug == slug, models.Note.status == "published")
        )
    ).first()
    if row is None:
        return HTMLResponse(
            _PAGE.format(
                title="Note not found — DRIFTIQ",
                meta="",
                body="<h1>Note not found</h1><p>This note does not exist or has not been published.</p>",
            ),
            status_code=404,
        )
    note, lecture = row
    date = lecture.created_at.strftime("%d %b %Y") if lecture.created_at else ""
    meta_bits = [b for b in [html.escape(lecture.subject or ""), date] if b]
    return HTMLResponse(
        _PAGE.format(
            title=f"{html.escape(lecture.subject or 'Lecture')} — DRIFTIQ Notes",
            meta=" · ".join(meta_bits),
            body=md_to_html(note.markdown),
        )
    )
